"""Type stub for the Mojo extension module built from ``_mojo/_core.mojo``."""

from typing import Any

class _Bank:
    def __init__(self, sample_rate: float, channels: int, /) -> None: ...
    def param_names(self) -> list[str]: ...
    def input_names(self) -> list[str]: ...
    def set(self, param: int, value: float, /) -> None: ...
    def reset(self) -> None: ...
    def process(self, src: int, dst: int, frames: int, mods: list[int], /) -> None: ...

class Phasor(_Bank): ...
class Sine(_Bank): ...
class Saw(_Bank): ...
class Square(_Bank): ...
class OnePole(_Bank): ...
class Biquad(_Bank): ...
class Svf(_Bank): ...
class Gain(_Bank): ...
class Scale(_Bank): ...
class Mix(_Bank): ...
class Adsr(_Bank): ...
class Noise(_Bank): ...
class Compressor(_Bank): ...
class Shaper(_Bank): ...
class Reverb(_Bank): ...
class Chorus(_Bank): ...
class Pan(_Bank): ...
class Width(_Bank): ...
class Delay(_Bank): ...

class Graph:
    def __init__(self, sample_rate: float, channels: int, block: int, /) -> None: ...
    def add(self, kind: str, /) -> int: ...
    def connect(self, src: int, dst: int, port: int, delay: int, /) -> None: ...
    def set(self, node: int, param: int, value: float, /) -> None: ...
    def remove(self, node: int, /) -> None: ...
    def set_output(self, node: int, /) -> None: ...
    def input_names(self, node: int, /) -> list[str]: ...
    def param_names(self, node: int, /) -> list[str]: ...
    def reset_node(self, node: int, /) -> None: ...
    def reset(self) -> None: ...
    def render(self, src: int, dst: int, frames: int, /) -> None: ...

def node_kinds() -> list[str]: ...
def audio_devices() -> list[dict[str, Any]]: ...

class Stream:
    def __init__(self, graph: Graph, /) -> None: ...
    def start(
        self,
        device: int,
        channels: int,
        sample_rate: float,
        block: int,
        input_device: int,
        /,
    ) -> None: ...
    def stop(self) -> None: ...
    def running(self) -> bool: ...
    def set(self, node: int, param: int, value: float, /) -> bool: ...
    def stats(self) -> dict[str, Any]: ...
