"""Type stub for the Mojo extension module built from ``_mojo/_core.mojo``."""

class _Bank:
    def __init__(self, sample_rate: float, channels: int, /) -> None: ...
    def param_names(self) -> list[str]: ...
    def set(self, param: int, value: float, /) -> None: ...
    def reset(self) -> None: ...
    def process(self, src: int, dst: int, frames: int, /) -> None: ...

class Phasor(_Bank): ...
class Sine(_Bank): ...
class Saw(_Bank): ...
class Square(_Bank): ...
class OnePole(_Bank): ...
class Biquad(_Bank): ...
class Gain(_Bank): ...
class Delay(_Bank): ...
